### ISSUE TITLE
zabbix_redis_stats.py: an exeption not handled and cause the daemon to die

### ISSUE THREAD

**Issue by pbychikhin** [pbychikhin/ZabbixUtils#37]
The log message:
Aug 16 00:28:51 a_host zabbix_redis_stats[7428][a_zabbix_host][ERROR]: Problem sending data to Zabbix server Traceback (most recent call last):   File "/usr/local/lib/python3.6/site-packages/pyzabbix/sender.py", line 398, in _chunk_send     connection.connect(host_addr) ConnectionRefusedError: [Errno 61] Connection refused  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/bin/zabbix_redis_stats.py", line 82, in do_main_program     pyzabbix.ZabbixSender(**zconn_vars).send(zbx_packet)   File "/usr/local/lib/python3.6/site-packages/pyzabbix/sender.py", line 433, in send     result.parse(self._chunk_send(metrics[m:m + self.chunk_size]))   File "/usr/local/lib/python3.6/site-packages/pyzabbix/sender.py", line 408, in _chunk_send     logger.warn('Sending failed: %s', err.msg) AttributeError: 'ConnectionRefusedError' object has no attribute 'msg'

Probably the issue relates to the pyzabbix.

**Comment by pbychikhin** [comment]
Probably, this is the real issue:
Traceback (most recent call last):
  File "/usr/local/bin/zabbix_redis_stats.py", line 134, in <module>
    do_main_program(cmdargs)
  File "/usr/local/bin/zabbix_redis_stats.py", line 74, in do_main_program
    redis_info["keyspace_misses"])
ZeroDivisionError: division by zero

This happens when Redis has just been restarted and its counters are zero because no requests received.

**Comment by pbychikhin** [comment]
Resolved in 6326ce63
