### ISSUE TITLE
zabbix_IIS_checker.py: relative paths don't work for directories

### ISSUE THREAD

**Issue by pbychikhin** [pbychikhin/ZabbixUtils#7]
When in config I set 
logfile=compressed\\zabbix_IIS_checker.log
I get the following:
Python could not construct the class instance 
Traceback (most recent call last):
  File "C:\zabbix_agents\py_scripts\zabbix_IIS_checker.py", line 736, in __init__
    **log_params)
  File "C:\Program Files\Python35\lib\logging\__init__.py", line 1745, in basicConfig
    h = FileHandler(filename, mode)
  File "C:\Program Files\Python35\lib\logging\__init__.py", line 1009, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Program Files\Python35\lib\logging\__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Python35\\lib\\site-packages\\win32\\compressed\\zabbix_IIS_checker.log'

**Comment by pbychikhin** [comment]
Fixed in 3cc85dd
